// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package querygen

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Link struct {
	Url           string
	Title         string
	Tags          pqtype.NullRawMessage
	CommentsCount int32
	ViewsCount    int32
	Rating        int32
	PublishedAt   time.Time
	Author        pqtype.NullRawMessage
	Complexity    int16
	Status        int16
}

type LinksQueue struct {
	AddedAt  time.Time
	Url      string
	PickedAt sql.NullTime
}

type TelegramUser struct {
	ID    int64
	Login string
}
