http:
  port: 8100

telegram:
  token: "${TELEGRAM_BOT_TOKEN}"

database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  database: ${DATABASE_NAME}
  user: ${DATABASE_USER}
  password: "${DATABASE_PASSWORD}"
  schema: public
  time-zone: UTC
  migrations-path: ${MIGRATIONS_PATH}
  connect-timeout: 5s

worker:
  worker-count: 10
  job-buffer-size: 10

processor:
  pick-interval: 5s
