version: "3"

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U user -d test'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
  warehouse:
    build:
      context: ../../
      dockerfile: ./build/docker/Dockerfile
    env_file:
      - ../../.env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: test
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
      MIGRATIONS_PATH: /app/migrations
    depends_on:
      - postgres
    configs:
      - source: warehouse
        target: /app/config.yaml

configs:
  warehouse:
    file: ../../configs/config.yaml
